const { env } = process;
const MONGO_URI = env.MONGO_URI;
const MAILTRAP_USER = env.MAILTRAP_USER;
const MAILTRAP_PASS = env.MAILTRAP_PASS;
const JWT_SECRET = env.JWT_SECRET;
const CLOUD_NAME = env.CLOUD_NAME;
const CLOUD_API_KEY = env.CLOUD_API_KEY;
const CLOUD_API_SECRET = env.CLOUD_API_SECRET;

module.exports = {
  MONGO_URI,
  MAILTRAP_USER,
  MAILTRAP_PASS,
  JWT_SECRET,
  CLOUD_API_KEY,
  CLOUD_NAME,
  CLOUD_API_SECRET,
};
